### ISSUE TITLE
ТРиТПО недосказанность

### ISSUE THREAD

**Issue by amateomi** [Joposhnick/BSUIR#1]
https://github.com/Joposhnick/BSUIR/blob/07c74268039cfdbfb534ddcea4c05f75c1bc9cc6/Semester_5/TRITPO/TRITPO_Lab_2/My_requirements.md?plain=1#L112

Из контекста предложения не ясно, о какой тематике идет речь, скорее всего, о военной.
Рекомендую явно это указать.

**Comment by SkibiDima** [comment]
Спасибо, уже исправлено и ждет git push'a. Обязательно присылайте еще фидбек

**Comment by Xotab413** [comment]
> https://github.com/Joposhnick/BSUIR/blob/07c74268039cfdbfb534ddcea4c05f75c1bc9cc6/Semester_5/TRITPO/TRITPO_Lab_2/My_requirements.md?plain=1#L112
> 
А как же женский пол ?)
