### ISSUE TITLE
ТРиТПО интернет

### ISSUE THREAD

**Issue by amateomi** [Joposhnick/BSUIR#2]
https://github.com/Joposhnick/BSUIR/blob/07c74268039cfdbfb534ddcea4c05f75c1bc9cc6/Semester_5/TRITPO/TRITPO_Lab_2/My_requirements.md?plain=1#L122

Предусматривает ли приложение игру по локальной сети? Скорее всего, это будет возможно. Таким образом для игры с друзьями по сети не понадобится Интернет.

**Comment by SkibiDima** [comment]
Нет, продукт не предусматривает поддержку игры по локальной сети. Спасибо за фидбек
