### ISSUE TITLE
ТРиТПО ограничения

### ISSUE THREAD

**Issue by amateomi** [Joposhnick/BSUIR#3]
https://github.com/Joposhnick/BSUIR/blob/07c74268039cfdbfb534ddcea4c05f75c1bc9cc6/Semester_5/TRITPO/TRITPO_Lab_2/My_requirements.md?plain=1#L200

Желательно добавить конкретику по поводу ограничений. На каких ОС можно будет играть? Какие минимальные и рекомендованные требования к ПК?

**Comment by SkibiDima** [comment]
Команда разработчиков еще не рассчитала предварительные требования к мощности персональной ЭВМ. По поводу ОС: игра точно будет поддерживаться Windows 98

**Comment by amateomi** [comment]
Но как же вы напишите игру на C# в Unity под ОС, которая вышла в 98 году прошлого века?

**Comment by SkibiDima** [comment]
Я всего лишь разрабатываю требования, писать-то не мне — и это хорошо
