### ISSUE TITLE
Больше опечаток

### ISSUE THREAD

**Issue by IvanGrigorik** [Joposhnick/BSUIR#5]
"Имзенить"
https://github.com/Joposhnick/BSUIR/blob/6eb3184b16d98c94408847d44121c4fa5bbf913c/Semester_5/TRITPO/TRITPO_Lab_2/My_requirements.md?plain=1#L165

"Значечения" - я не за чечню.
https://github.com/Joposhnick/BSUIR/blob/6eb3184b16d98c94408847d44121c4fa5bbf913c/Semester_5/TRITPO/TRITPO_Lab_2/My_requirements.md?plain=1#L167

"возможножность"
https://github.com/Joposhnick/BSUIR/blob/6eb3184b16d98c94408847d44121c4fa5bbf913c/Semester_5/TRITPO/TRITPO_Lab_2/My_requirements.md?plain=1#L155

**Comment by SkibiDima** [comment]
Вы молодец, нашли все специально подложенные опечатки в рамках нашего теста на внимательнотсь! Мы учтем ваши предложения
